import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'A. Tecnica',
      items: [
        {type: 'autogenerated', dirName: 'A_Tecnica/01_Elettricita'},
        {type: 'autogenerated', dirName: 'A_Tecnica/02_Componenti'},
        {type: 'autogenerated', dirName: 'A_Tecnica/03_Circuiti'},
        {type: 'autogenerated', dirName: 'A_Tecnica/04_Ricevitori'},
        {type: 'autogenerated', dirName: 'A_Tecnica/05_Trasmettitori'},
        {type: 'autogenerated', dirName: 'A_Tecnica/06_Antenne'},
        {type: 'autogenerated', dirName: 'A_Tecnica/07_Propagazione'},
        {type: 'autogenerated', dirName: 'A_Tecnica/08_Misure'},
        {type: 'autogenerated', dirName: 'A_Tecnica/09_Disturbi'},
        {type: 'autogenerated', dirName: 'A_Tecnica/10_Protezione'},
      ],
    },
    {
      type: 'category',
      label: 'B. Operativa',
      items: [{type: 'autogenerated', dirName: 'B_Operativa'}],
    },
    {
      type: 'category',
      label: 'C. Regolamentazione',
      items: [{type: 'autogenerated', dirName: 'C_Regolamentazione'}],
    },
  ],
};

export default sidebars;
